apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
      - name: card-service
        image: govo-card-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        - containerPort: 50054
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: carddb
        - name: HTTP_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "50054"
---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 50054
    targetPort: 50054 