apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "name": "Govo API Gateway",
      "cache_ttl": "3600s",
      "timeout": "3s",
      "extra_config": {
        "security/cors": {
          "allow_origins": ["*"],
          "allow_methods": ["GET", "POST", "PUT", "DELETE"],
          "allow_headers": ["Origin", "Authorization", "Content-Type"],
          "expose_headers": ["Content-Length"],
          "max_age": "12h"
        }
      },
      "endpoints": [
        {
          "endpoint": "/api/v1/cards/{id}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/cards/{id}",
              "host": ["http://card-service:8080"]
            }
          ]
        },
        {
          "endpoint": "/api/v1/payments",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/payments",
              "host": ["http://payment-service:8080"]
            }
          ]
        },
        {
          "endpoint": "/api/v1/customers",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/customers",
              "host": ["http://customer-service:8080"]
            }
          ]
        }
      ]
    } 