apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: govo-payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 50053
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: paymentdb
        - name: HTTP_PORT
          value: "8080"
        - name: GRPC_PORT
          value: "50053"
        - name: KAFKA_BROKERS
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50053
    targetPort: 50053 